name: i2v
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0
  - numpy=1.17.4
  - pip=19.3.1
  - python=3.7.5
  - pytorch=1.7.0
  - torchvision=0.8.1
  - pip:
    - gdown==3.12.2
    - gpustat==0.6.0
    - imageio==2.6.1
    - kornia==0.5.0
    - lpips==0.1
    - moviepy==1.0.3
    - natsort==7.0.0
    - omegaconf==2.0.5
    - opencv-contrib-python==4.1.2.30
    - pillow==7.2.0
    - pytorch-lightning==1.2.7
    - scikit-image==0.16.2
    - scikit-learn==0.23.1
    - scipy==1.5.3
    - sklearn==0.0
    - tqdm==4.41.1
    - wandb==0.10.26
    - tensorflow-gan==2.0.0
    - tensorflow-gpu==2.4.0
    - tensorflow-hub==0.9.0
    - tensorflow-probability==0.11.1
    - silence-tensorflow==1.1.1
    - iPython==7.22.0
