AE:
  deterministic: False
  in_size: 128
  norm: "bn"
  encoder_type: "resnet50"
  use_actnorm_in_dec: False
  z_dim: 128

Discriminator_Patch:
  in_channels: 3
  ndf: 64
  n_layers: 3
  use_actnorm: True
  spectral_norm: True

Training:
  w_kl: 1e-5
  n_epochs: 100
  lr: 2e-4
  bs: 30
  weight_decay: 0
  workers: 30
  pretrain: 20
  savename: 'INSERT_NAME_HERE'
  save_path: 'INSERT_PATH_HERE'

Data:
  sequence_length: 1
  img_size: 128
  dataset: 'DTDB'
  texture: 'waterfall'
  image_format: 'jpg'
  aug: True
  iter_train: 120
  iter_eval: 5
  iter_test: 6
  data_path: 'INSERT_DATA_PATH_HERE'
  Augmentation:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.15
    prob_hflip: 0.5

Logging:
  entity: 'INSERT_WANDB_NAME'
  project: "INSERT_PROJECT_NAME"
  mode: 'online'
